# Generated by Django 4.2.4 on 2023-09-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
